### ISSUE TITLE
Error: Got unexpected extra argument (300)

### ISSUE THREAD

**Issue by asomervell** [donaldpiret/ecs-deploy#1] opened 2020-04-05 03:16 UTC
Gidday, using this for an open source project, with the following config:

```
    - name: ECS Deployment
      uses: donaldpiret/ecs-deploy@v0.0.1
      with:
        cluster: vly-alpha-ECSCluster
        target: vly-alpha
        image: vly-alpha:latest
```

And I get the following, not sure how i'm introducing an extra param or getting the commands wrong?

```
Performing deploy
Command run: ecs deploy vly-alpha-ECSCluster vly-alphaTargetGroup -i vly-alpha:latest --timeout 300
Usage: ecs deploy [OPTIONS] CLUSTER SERVICE

Error: Got unexpected extra argument (300)
```

Thanks,

**Comment by donaldpiret** [comment] 2020-04-05 08:43
Hey @asomervell, the image parameter requires both the name of the container to update as well as the image, eg. in your case it would be (if your container name was "app"):

```
    - name: ECS Deployment
      uses: donaldpiret/ecs-deploy@v0.0.1
      with:
        cluster: vly-alpha-ECSCluster
        target: vly-alpha
        image: app vly-alpha:latest
```

Hope this helps.

**Comment by asomervell** [comment] 2020-04-05 09:27
> Hey @asomervell, the image parameter requires both the name of the container to update as well as the image, eg. in your case it would be (if your container name was "app"):

Will give it a go and report back! Thx

**Comment by asomervell** [comment] 2020-04-05 20:11
@donaldpiret so now we're at 
```
Performing deploy
Command run: ecs deploy vly-alpha-ECSCluster vly-alpha -i vly-alpha vly-alpha:latest --timeout 300
Deploying based on task definition: vly-alpha:16

Updating task definition
Changed image of container "vly-alpha" to: "vly-alpha:latest" (was: "vly-alpha:latest")

Creating new task definition revision
Successfully created revision: 17

Updating service
Successfully changed task definition to: vly-alpha:17

Deployment failed due to timeout. Please see: https://github.com/fabfuel/ecs-deploy#timeout

Deploying new task definition.........................................................................................................................................................................................................
```

Is there a way to get it to use a current task definition or does it have to iterate each time by design? I feel like it's not frightfully close.

Context: It's like a single node container replacing one running one, 300s should be plenty?

**Comment by donaldpiret** [comment] 2020-04-06 00:29
Hello,
The new task definition version is by design to ensure that it will fetch a new version of the docker image. If you are re-using the same docker tag and deploying the same task definition number it is possible that new tasks would re-use the docker image in cache.
It should clean up older versions of the task definition after a successful deployment. 
What would be the use-case behind not wanting to bump the task definition version?
Regarding the timeout, I would suggest checking to see if the new task version is coming up correctly. Timeout errors are generally due to problems bringing up the ask and ECS trying again over and over. If the task does come online successfully then you might have to increase your timeout time. 

Hope this helps!

**Comment by donaldpiret** [comment] 2020-05-03 07:59
Will close this issue as I assume it's been resolved. Let me know if you still encounter any issues.

**Closed as completed by donaldpiret** 2020-05-03 07:59 UTC
